import { describe, it, expect } from "vitest";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { discoverGeneratedFiles } from "../../src/ci/discover.js";
import { withTempDir, writeGenerated } from "./helpers.js";

describe("C-007 discoverGeneratedFiles", () => {
  it("returns [] when the forge's directory doesn't exist yet", async () => {
    await withTempDir(async (dir) => {
      expect(await discoverGeneratedFiles(dir, "github")).toEqual([]);
      expect(await discoverGeneratedFiles(dir, "gitlab")).toEqual([]);
    });
  });

  it("includes a file whose first line matches the header, at any version", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v1 — do not edit\nname: catalog-ci\n",
      );
      const found = await discoverGeneratedFiles(dir, "github");
      expect(found).toHaveLength(1);
      expect(found[0]).toMatchObject({ path: ".github/workflows/catalog-ci.yml", headerVersion: 1 });
    });
  });

  it("excludes a file with no header at all", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(dir, ".github/workflows/other.yml", "name: hand-written\n");
      expect(await discoverGeneratedFiles(dir, "github")).toEqual([]);
    });
  });

  it("excludes a file with a malformed header", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(dir, ".github/workflows/other.yml", "# Generated by something-else\n");
      expect(await discoverGeneratedFiles(dir, "github")).toEqual([]);
    });
  });

  it("ignores non-yaml files in the directory", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/README.md",
        "# generated by ocx-catalog ci v1 — do not edit\n",
      );
      expect(await discoverGeneratedFiles(dir, "github")).toEqual([]);
    });
  });

  it("scans the GitLab include directory (never the root .gitlab-ci.yml)", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(dir, ".gitlab-ci.yml", "# generated by ocx-catalog ci v1 — do not edit\n");
      await writeGenerated(
        dir,
        ".gitlab-ci/catalog.yml",
        "# generated by ocx-catalog ci v1 — do not edit\ncatalog:build:\n",
      );
      const found = await discoverGeneratedFiles(dir, "gitlab");
      expect(found).toHaveLength(1);
      expect(found[0]?.path).toBe(".gitlab-ci/catalog.yml");
    });
  });

  it("returns multiple matching files sorted by name", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(dir, ".github/workflows/b.yml", "# generated by ocx-catalog ci v1 — do not edit\n");
      await writeGenerated(dir, ".github/workflows/a.yml", "# generated by ocx-catalog ci v1 — do not edit\n");
      const found = await discoverGeneratedFiles(dir, "github");
      expect(found.map((f) => f.path)).toEqual([
        ".github/workflows/a.yml",
        ".github/workflows/b.yml",
      ]);
    });
  });

  it("returns [] for a forge directory that exists but is empty", async () => {
    await withTempDir(async (dir) => {
      await mkdir(join(dir, ".github/workflows"), { recursive: true });
      expect(await discoverGeneratedFiles(dir, "github")).toEqual([]);
    });
  });

  it("propagates a non-ENOENT readdir error instead of treating it as absent", async () => {
    await withTempDir(async (dir) => {
      // A plain file where the forge directory would be: readdir() on it
      // rejects ENOTDIR, not ENOENT, so this must NOT be swallowed into [].
      await writeFile(join(dir, ".github"), "not a directory");
      await expect(discoverGeneratedFiles(dir, "github")).rejects.toMatchObject({ code: "ENOTDIR" });
    });
  });
});
