import { describe, it, expect } from "vitest";
import { HEADER_LINE, TOOL_HEADER_VERSION, parseHeaderVersion } from "../../src/ci/header.js";

describe("C-007 header contract", () => {
  it("HEADER_LINE matches its own version and the executable-spec pattern", () => {
    expect(HEADER_LINE).toBe(`# generated by ocx-catalog ci v${TOOL_HEADER_VERSION} — do not edit`);
    expect(parseHeaderVersion(HEADER_LINE)).toBe(TOOL_HEADER_VERSION);
  });

  it("parses a known older version forever", () => {
    expect(parseHeaderVersion("# generated by ocx-catalog ci v1 — do not edit")).toBe(1);
  });

  it("parses a version newer than the tool's own (caller decides tool-too-old)", () => {
    expect(parseHeaderVersion("# generated by ocx-catalog ci v99 — do not edit")).toBe(99);
  });

  it("matches even with trailing content after 'do not edit' (no $ anchor in the spec pattern)", () => {
    expect(parseHeaderVersion("# generated by ocx-catalog ci v1 — do not edit, seriously")).toBe(1);
  });

  it("returns null for a missing header", () => {
    expect(parseHeaderVersion("name: some-other-workflow")).toBeNull();
  });

  it("returns null for a malformed header (wrong wording)", () => {
    expect(parseHeaderVersion("# Generated by @grimoire-rs/indexer")).toBeNull();
  });

  it("returns null for a malformed header (missing version digits)", () => {
    expect(parseHeaderVersion("# generated by ocx-catalog ci v — do not edit")).toBeNull();
  });

  it("returns null for an empty first line", () => {
    expect(parseHeaderVersion("")).toBeNull();
  });
});
