import { describe, it, expect, vi } from "vitest";
import { CiError } from "../../src/ci/errors.js";
import { HEADER_LINE } from "../../src/ci/header.js";
import { DEFAULT_PINS } from "../../src/ci/pins.js";
import { renderCi } from "../../src/ci/render.js";
import { withTempDir, writeGenerated } from "./helpers.js";

/** Stands in for a Renovate-bumped pin — a real 40-hex SHA, since a
 * carried-forward ref that isn't one is dropped by design (security panel
 * W4, `pins.ts`' `COMMIT_SHA_RE`). Deliberately different from every
 * `DEFAULT_PINS` value, so "carried forward" and "fell back to the default"
 * can't be confused. */
const RENOVATED_SHA = "1f0e3dad99908345f7439f8ffabdffc4a1f0e3da";

describe("C-007 renderCi", () => {
  it("renders the github job set with template-default pins on a first render", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "github" }, dir);
      expect(files).toHaveLength(1);
      expect(files[0]?.path).toBe(".github/workflows/catalog-ci.yml");
      const content = files[0]?.content ?? "";
      expect(content.split("\n")[0]).toBe("# generated by ocx-catalog ci v1 — do not edit");
      expect(content).toContain(`uses: actions/checkout@${DEFAULT_PINS["actions/checkout"]}`);
      expect(content).toContain("verify-catalog-ci:");
      expect(content.endsWith("\n")).toBe(true);
      expect(content.endsWith("\n\n")).toBe(false);
    });
  });

  it("renders the gitlab job set as an included file, not the root", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "gitlab" }, dir);
      expect(files).toHaveLength(1);
      expect(files[0]?.path).toBe(".gitlab-ci/catalog.yml");
      expect(files[0]?.content).toContain("catalog:build:");
      expect(files[0]?.content).toContain("catalog:verify:");
    });
  });

  it("omits the verify job when verifyCi is false", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "github", verifyCi: false }, dir);
      const content = files[0]?.content ?? "";
      expect(content).not.toContain("verify-catalog-ci:");
      expect(content.endsWith("\n")).toBe(true);
      expect(content.endsWith("\n\n")).toBe(false);
    });
  });

  it("gitlab: omits the verify job when verifyCi is false", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "gitlab", verifyCi: false }, dir);
      expect(files[0]?.content).not.toContain("catalog:verify:");
    });
  });

  it("includes the verify job by default (verifyCi absent)", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "github" }, dir);
      expect(files[0]?.content).toContain("verify-catalog-ci:");
    });
  });

  it("carries forward a pin scraped from a committed generated file (S-004)", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v1 — do not edit\n" +
          `      - uses: actions/checkout@${RENOVATED_SHA}  # v4.9.9\n`,
      );
      const files = await renderCi({ forge: "github" }, dir);
      expect(files[0]?.content).toContain(`uses: actions/checkout@${RENOVATED_SHA}  # v4.9.9`);
    });
  });

  // Security panel WARN (2026-08-22, W4): a hand-edit to `@main` is invisible
  // to the generated drift job, so the render must never adopt it as the new
  // pin — the template default (a real SHA) wins, loudly.
  it("a mutable ref in a committed generated file falls back to the default and warns on stderr", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v1 — do not edit\n" + "      - uses: actions/checkout@main\n",
      );
      const errSpy = vi.spyOn(process.stderr, "write").mockImplementation(() => true);
      const files = await renderCi({ forge: "github" }, dir);
      expect(files[0]?.content).toContain(`uses: actions/checkout@${DEFAULT_PINS["actions/checkout"]}`);
      expect(files[0]?.content).not.toContain("uses: actions/checkout@main");
      expect(errSpy).toHaveBeenCalledWith(
        expect.stringContaining("committed pin for actions/checkout is not a 40-hex commit SHA"),
      );
      errSpy.mockRestore();
    });
  });

  it("conflicting pins across generated files fall back to the default and warn on stderr", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v1 — do not edit\n" +
          `      - uses: actions/checkout@${"a".repeat(40)}  # v4.3.0\n`,
      );
      await writeGenerated(
        dir,
        ".github/workflows/stale.yml",
        "# generated by ocx-catalog ci v1 — do not edit\n" +
          `      - uses: actions/checkout@${"b".repeat(40)}  # v4.3.1\n`,
      );
      const errSpy = vi.spyOn(process.stderr, "write").mockImplementation(() => true);
      const files = await renderCi({ forge: "github" }, dir);
      expect(files[0]?.content).toContain(`uses: actions/checkout@${DEFAULT_PINS["actions/checkout"]}`);
      expect(errSpy).toHaveBeenCalledWith(expect.stringContaining("conflicting committed pins for actions/checkout"));
      errSpy.mockRestore();
    });
  });

  it("no discovered files: no stderr warning at all", async () => {
    await withTempDir(async (dir) => {
      const errSpy = vi.spyOn(process.stderr, "write").mockImplementation(() => true);
      await renderCi({ forge: "github" }, dir);
      expect(errSpy).not.toHaveBeenCalled();
      errSpy.mockRestore();
    });
  });

  it("packageManager absent renders byte-identical output to explicit npm", async () => {
    await withTempDir(async (dir) => {
      const withDefault = await renderCi({ forge: "github" }, dir);
      const explicitNpm = await renderCi({ forge: "github", packageManager: "npm" }, dir);
      expect(explicitNpm[0]?.content).toBe(withDefault[0]?.content);
    });
  });

  // C-0XX packageManager: the byte-exact reconstruction this test compares
  // against is what this renderer's templates produced BEFORE `{{setupSteps}}`
  // / `{{installCmd}}` / `{{execPrefix}}` existed (github-ci.yml +
  // github-verify-job.yml, hardcoded npm) — "packageManager absent or npm
  // must never change rendered output" is the hard requirement this locks in.
  it("packageManager npm reproduces the pre-packageManager github template output byte-for-byte", async () => {
    await withTempDir(async (dir) => {
      const expected =
        `${HEADER_LINE}\n` +
        "#\n" +
        "# Rendered by `ocx-catalog ci` from this repository's own catalog.config.json\n" +
        "# `ci` block. Do not hand-edit this file — change the config instead and\n" +
        "# re-render:\n" +
        "#\n" +
        "#     npx ocx-catalog ci\n" +
        "#\n" +
        "# `ci.verifyCi: false` in catalog.config.json omits the verify-catalog-ci job\n" +
        "# below (`ocx-catalog ci --check`) and stops CI from catching a hand-edit —\n" +
        "# the repository then owns this file by hand instead.\n" +
        "name: catalog-ci\n" +
        "\n" +
        "on:\n" +
        "  pull_request:\n" +
        "  push:\n" +
        "    branches: [main]\n" +
        "\n" +
        "permissions: {}\n" +
        "\n" +
        "jobs:\n" +
        "  build:\n" +
        "    name: build\n" +
        "    runs-on: ubuntu-latest\n" +
        "    permissions:\n" +
        "      contents: read\n" +
        "    steps:\n" +
        `      - uses: actions/checkout@${DEFAULT_PINS["actions/checkout"]}\n` +
        "        with:\n" +
        "          persist-credentials: false\n" +
        `      - uses: actions/setup-node@${DEFAULT_PINS["actions/setup-node"]}\n` +
        "        with:\n" +
        '          node-version: "22"\n' +
        "          cache: npm\n" +
        "      - run: npm ci\n" +
        "      - run: npx ocx-catalog build\n" +
        "\n" +
        "  verify-catalog-ci:\n" +
        "    name: verify-catalog-ci\n" +
        "    runs-on: ubuntu-latest\n" +
        "    permissions:\n" +
        "      contents: read\n" +
        "    steps:\n" +
        `      - uses: actions/checkout@${DEFAULT_PINS["actions/checkout"]}\n` +
        "        with:\n" +
        "          persist-credentials: false\n" +
        `      - uses: actions/setup-node@${DEFAULT_PINS["actions/setup-node"]}\n` +
        "        with:\n" +
        '          node-version: "22"\n' +
        "          cache: npm\n" +
        "      - run: npm ci\n" +
        "      - run: npx ocx-catalog ci --check\n";
      const files = await renderCi({ forge: "github", packageManager: "npm" }, dir);
      expect(files[0]?.content).toBe(expected);
    });
  });

  it("carries forward a committed actions/setup-node pin (npm)", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v1 — do not edit\n" +
          `      - uses: actions/setup-node@${RENOVATED_SHA}  # v8.0.0\n`,
      );
      const files = await renderCi({ forge: "github" }, dir);
      expect(files[0]?.content).toContain(`uses: actions/setup-node@${RENOVATED_SHA}  # v8.0.0`);
    });
  });

  it("packageManager bun renders oven-sh/setup-bun in place of actions/setup-node, with bun install/exec commands (github)", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "github", packageManager: "bun" }, dir);
      const content = files[0]?.content ?? "";
      expect(content).toContain(`uses: oven-sh/setup-bun@${DEFAULT_PINS["oven-sh/setup-bun"]}`);
      expect(content).not.toContain("actions/setup-node");
      expect(content).not.toContain("cache: npm");
      expect(content).toContain("- run: bun install --frozen-lockfile");
      expect(content).toContain("- run: bun x ocx-catalog build");
      expect(content).toContain("- run: bun x ocx-catalog ci --check");
    });
  });

  it("carries forward a committed oven-sh/setup-bun pin (bun)", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v1 — do not edit\n" +
          `      - uses: oven-sh/setup-bun@${RENOVATED_SHA}  # v2.9.9\n`,
      );
      const files = await renderCi({ forge: "github", packageManager: "bun" }, dir);
      expect(files[0]?.content).toContain(`uses: oven-sh/setup-bun@${RENOVATED_SHA}  # v2.9.9`);
    });
  });

  it("packageManager bun renders the oven/bun:1 image with bun install/exec commands (gitlab)", async () => {
    await withTempDir(async (dir) => {
      const files = await renderCi({ forge: "gitlab", packageManager: "bun" }, dir);
      const content = files[0]?.content ?? "";
      expect(content).toContain("image: oven/bun:1");
      expect(content).not.toContain("node:22-alpine");
      expect(content).toContain("- bun install --frozen-lockfile");
      expect(content).toContain("- bun x ocx-catalog build");
      expect(content).toContain("- bun x ocx-catalog ci --check");
    });
  });

  it("throws TOOL_TOO_OLD when a committed file names a newer header version", async () => {
    await withTempDir(async (dir) => {
      await writeGenerated(
        dir,
        ".github/workflows/catalog-ci.yml",
        "# generated by ocx-catalog ci v99 — do not edit\nname: catalog-ci\n",
      );
      const error = await renderCi({ forge: "github" }, dir).catch((err: unknown) => err);
      expect(error).toBeInstanceOf(CiError);
      expect((error as CiError).code).toBe("TOOL_TOO_OLD");
      expect((error as CiError).message).toContain(".github/workflows/catalog-ci.yml");
      expect((error as CiError).message).toContain("v99");
    });
  });
});
