/**
 * C-305: not a bot transcription like the other cases — pins
 * `catalogIndex`'s multi-PACKAGE merge behavior, which no other golden case
 * exercises (every other `input.ts` carries exactly one `packageId` entry).
 * Expected output: `../expected/catalog.json`, generated by actually
 * running `catalogIndex`+`serializeCatalog` against this module (never
 * hand-typed).
 *
 * Two packages, deliberately ordered `zebra` THEN `apple` — the opposite of
 * alphabetical — to prove `catalogIndex` preserves `ordered`'s own sequence
 * rather than re-sorting (matching `catalogIndex`'s own doc: "does not
 * itself sort"). `zebra` (first entry) carries the OLDER activity and a
 * variant-prefixed tag (`musl-2.0.0`, exercising `variants` in a
 * multi-package merge for the first time); `apple` (second entry, no desc)
 * carries the NEWER activity — so `generated` resolving to `apple`'s
 * timestamp proves `generatedTimestamp` scans every package in `ordered`,
 * not just the first.
 */
import type { CatalogSourcePackage } from "../../../src/viewmodel/types.js";
import { digest, indexBytes, utf8 } from "../_helpers.js";

export const ordered: readonly CatalogSourcePackage[] = [
  {
    packageId: { namespace: "acme", package: "zebra" },
    root: {
      name: "ocx.sh/acme/zebra",
      status: "active",
      deprecatedMessage: null,
      supersededBy: null,
      created: "2026-01-01",
      desc: {
        title: "Zebra",
        description: "Striped build tool.",
        keywords: ["build", "zebra"],
        readme: digest("e"),
        logo: digest("f"),
      },
      tags: {
        "2.0.0": { content: digest("g"), observed: "2026-01-01T00:00:00Z", yanked: null },
        "musl-2.0.0": { content: digest("h"), observed: "2026-01-02T00:00:00Z", yanked: null },
      },
    },
    contentByDigest: {
      [`${digest("g")}.json`]: indexBytes("2.0.0"),
      [`${digest("h")}.json`]: indexBytes("musl-2.0.0", [{ architecture: "amd64", os: "linux" }]),
      [`${digest("e")}.md`]: utf8("# Zebra\n\nStriped build tool.\n"),
      [`${digest("f")}.svg`]: utf8("<svg>zebra-logo</svg>"),
    },
  },
  {
    packageId: { namespace: "acme", package: "apple" },
    root: {
      name: "ocx.sh/acme/apple",
      status: "active",
      deprecatedMessage: null,
      supersededBy: null,
      created: "2026-08-01",
      desc: null,
      tags: {
        "1.0.0": { content: digest("i"), observed: "2026-08-11T00:00:00Z", yanked: null },
      },
    },
    contentByDigest: {
      [`${digest("i")}.json`]: indexBytes("1.0.0"),
    },
  },
];
