/**
 * C-305: pins `catalogIndex`/`serializeCatalog`'s zero-package path — no
 * other golden case exercises an empty `ordered` array. Expected output:
 * `../expected/catalog.json` (`{ "generated": null, "packages": [] }`),
 * generated by actually running the emitter against this module (never
 * hand-typed). `generated: null` proves `generatedTimestamp`'s "no package
 * has ever carried a tag" fallback fires on the whole-catalog case, not just
 * a single package with no tags.
 */
import type { CatalogSourcePackage } from "../../../src/viewmodel/types.js";

export const ordered: readonly CatalogSourcePackage[] = [];
