/**
 * The generated-file header contract (C-007). Every file this module writes
 * starts with this exact line (see `HEADER_LINE`); every file it reads
 * treats this same pattern, matched against ANY version number, as the
 * signal "this file is ours" — never a fixed filename or directory listing.
 *
 * The header is itself a versioned contract: bump `TOOL_HEADER_VERSION` only
 * when the render/discovery/normalize contract changes in a way an older
 * tool version could no longer safely parse. A file whose header names a
 * version greater than this tool's own is refused (`TOOL_TOO_OLD` — the
 * installed `@ocx-sh/catalog` is older than whatever last rendered it); a
 * file naming an older version must go on being parsed and scraped for pins
 * forever, which is why `parseHeaderVersion` has no per-version branching —
 * the pattern itself doesn't change across versions, only the number in it.
 */
export const TOOL_HEADER_VERSION = 1;

const HEADER_PATTERN = /^# generated by ocx-catalog ci v(\d+) — do not edit/;

/** The literal first line of every file this tool renders. */
export const HEADER_LINE = `# generated by ocx-catalog ci v${TOOL_HEADER_VERSION} — do not edit`;

/**
 * Matches `firstLine` against the header contract, returning the version
 * number it names or `null` when the line doesn't match at all — a missing
 * or malformed header, which the caller must treat as "not ours": never
 * scraped for pins, never drift-checked, silently skipped.
 */
export function parseHeaderVersion(firstLine: string): number | null {
  const match = HEADER_PATTERN.exec(firstLine);
  return match === null ? null : Number(match[1]);
}
