import type { CiConfig } from "../config/types.js";
import { discoverGeneratedFiles } from "./discover.js";
import { CiError } from "./errors.js";
import { HEADER_LINE, TOOL_HEADER_VERSION } from "./header.js";
import { DEFAULT_PINS, scrapePins, type ScrapedPins } from "./pins.js";
import { renderTemplate } from "./templates.js";

/** One rendered file, repo-root-relative path + full content. */
export interface RenderedFile {
  path: string;
  content: string;
}

const GITHUB_FILE = ".github/workflows/catalog-ci.yml";
const GITLAB_FILE = ".gitlab-ci/catalog.yml";

/** Per-`ci.packageManager` install/exec commands + GitLab base image — the
 * lookup table `renderCi` uses to fill `{{installCmd}}`/`{{execPrefix}}`/
 * `{{image}}`. The `npm` row reproduces this renderer's pre-packageManager
 * output byte-for-byte (see render.test.ts); `bun` swaps in bun's own
 * install/exec/image since a bun repo has no `package-lock.json` for
 * `npm ci` to read. */
const PACKAGE_MANAGER: Record<"npm" | "bun", { installCmd: string; execPrefix: string; gitlabImage: string }> = {
  npm: { installCmd: "npm ci", execPrefix: "npx", gitlabImage: "node:22-alpine" },
  bun: { installCmd: "bun install --frozen-lockfile", execPrefix: "bun x", gitlabImage: "oven/bun:1" },
};

/** Collapses any run of trailing newlines to exactly one — an omitted
 * `{{verifyJob}}` block otherwise leaves a stray blank line at EOF. */
function finalizeFile(content: string): string {
  return content.replace(/\n*$/, "\n");
}

/** Both reasons a committed pin can't be carried forward end the same way —
 * the template default is used — but they say different things to whoever
 * has to fix it: two files disagreeing, versus a `uses:` ref that isn't a
 * commit SHA at all (security panel W4, see `pins.ts`' `COMMIT_SHA_RE`). */
function warnUnusablePins({ conflicts, mutableRefs }: ScrapedPins): void {
  for (const action of conflicts) {
    process.stderr.write(
      `ocx-catalog ci: conflicting committed pins for ${action} — using the template default\n`,
    );
  }
  for (const action of mutableRefs) {
    process.stderr.write(
      `ocx-catalog ci: committed pin for ${action} is not a 40-hex commit SHA (mutable ref) — ` +
        `using the template default\n`,
    );
  }
}

/** The GitHub Actions setup step(s) for `packageManager`, fully rendered
 * (pin already substituted) before it's handed to `renderTemplate` as a
 * value — a placeholder inside a substituted value is never re-scanned
 * (see templates.ts's own doc comment). npm needs `actions/setup-node`'s
 * `cache: npm`; bun ships its own runtime, so `oven-sh/setup-bun` replaces
 * setup-node outright rather than running alongside it. */
function githubSetupSteps(packageManager: "npm" | "bun", pins: ReadonlyMap<string, string>): string {
  if (packageManager === "bun") {
    const pin = pins.get("oven-sh/setup-bun") ?? (DEFAULT_PINS["oven-sh/setup-bun"] as string);
    return `      - uses: oven-sh/setup-bun@${pin}`;
  }
  const pin = pins.get("actions/setup-node") ?? (DEFAULT_PINS["actions/setup-node"] as string);
  return `      - uses: actions/setup-node@${pin}\n        with:\n          node-version: "22"\n          cache: npm`;
}

/**
 * Renders the catalog CI job set for `ci.forge` (C-007). Does not touch
 * disk beyond reading whatever generated files already exist, for pin
 * carry-forward and the header-version check — the caller (`write.ts`)
 * writes or diffs the result.
 *
 * Throws `CiError("TOOL_TOO_OLD")` when a discovered file's header names a
 * version newer than this tool supports.
 */
export async function renderCi(ci: CiConfig, repoRoot: string): Promise<RenderedFile[]> {
  const verifyCi = ci.verifyCi ?? true;
  const packageManager = ci.packageManager ?? "npm";
  const discovered = await discoverGeneratedFiles(repoRoot, ci.forge);

  for (const file of discovered) {
    if (file.headerVersion > TOOL_HEADER_VERSION) {
      throw new CiError(
        "TOOL_TOO_OLD",
        `${file.path}: generated by ocx-catalog ci v${file.headerVersion}, but this ` +
          `installed @ocx-sh/catalog only supports up to v${TOOL_HEADER_VERSION} — upgrade the package`,
      );
    }
  }

  const scraped = scrapePins(discovered);
  const { pins } = scraped;
  warnUnusablePins(scraped);
  const { installCmd, execPrefix, gitlabImage } = PACKAGE_MANAGER[packageManager];
  const vars: Record<string, string> = {
    header: HEADER_LINE,
    checkoutPin: pins.get("actions/checkout") ?? (DEFAULT_PINS["actions/checkout"] as string),
    setupSteps: githubSetupSteps(packageManager, pins),
    installCmd,
    execPrefix,
    image: gitlabImage,
  };

  if (ci.forge === "github") {
    const verifyJob = verifyCi ? `\n${renderTemplate("ci/github-verify-job.yml", vars).replace(/\n+$/, "")}` : "";
    const content = renderTemplate("ci/github-ci.yml", { ...vars, verifyJob });
    return [{ path: GITHUB_FILE, content: finalizeFile(content) }];
  }

  const verifyJob = verifyCi ? `\n${renderTemplate("ci/gitlab-verify-job.yml", vars).replace(/\n+$/, "")}` : "";
  const content = renderTemplate("ci/gitlab-ci.yml", { ...vars, verifyJob });
  return [{ path: GITLAB_FILE, content: finalizeFile(content) }];
}
