// The Vite virtual module `src/site/integration.ts` serves from `site.json`
// (C-047). Pages read route keys / docs slugs from it in `getStaticPaths`.
declare module "virtual:ocx-catalog/site" {
  import type { SiteModel } from "./model/index.js";
  const site: SiteModel;
  export default site;
}

// The theme ships `csp.d.mts` only in its packed tarball (generated by `prepack`);
// a `file:`-linked checkout has none. Same shape as that generated file.
declare module "@ocx-sh/theme/csp" {
  /** `sha256-<base64>` script-src sources of the Shell's inline scripts, without quotes. */
  export const INLINE_SCRIPT_HASHES: readonly string[];
}
